package fr.roman.vues.edition;

public enum LibelleChamp {
  TEXTFIELD,
  SPINNERDOUBLE,
  SPINNERINT,
  CALENDEARTIMETEXTFIELD,
  CALENDEARTEXTFIELD,
  CHECKBOX,
  DOUBLESPINNERDOUBLE,
  BUTTON,
  COMMANDE,
  VEHICULE
}
